### ISSUE TITLE
Make a  proper documentation on how to use it! 

### ISSUE THREAD

**Issue by the-wrong-guy** [SahajR/react-star-review#5]
After installing the package how to use use it? Give some proper documentation

**Comment by SahajR** [comment]
You can view the demo code here: https://github.com/SahajR/react-star-review/blob/master/src/demo/App.js

Let me know if that helps.

**Comment by the-wrong-guy** [comment]
> You can view the demo code here: https://github.com/SahajR/react-star-review/blob/master/src/demo/App.js
> 
> Let me know if that helps.

Thanks, add this in the readme, it will help others
